openapi: 3.0.4
info:
  title: Registration API
  version: 1.0.3
paths:
  /register:
    post:
      summary: Регистрация нового пользователя
      description: API для регистрации пользователя. Вызывается фронтендом при нажатии на кнопку "Register"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - username
                - password
                - recaptchaToken
              properties:
                firstname:
                  type: string
                  description: Имя пользователя
                  minLength: 3
                  maxLength: 50
                lastname:
                  type: string
                  description: Фамилия пользователя
                  minLength: 3
                  maxLength: 50
                username:
                  type: string
                  description: Никнейм
                  minLength: 3
                  maxLength: 50
                password:
                  type: string
                  description: пароль пользователя
                  minLength: 8
                  maxLength: 128
                  pattern: '^(?=.*\d)(?=.*[A-Z])(?=.*[a-z].{8,}$)'
                recaptchaToken:
                  type: string
                  description: Токен от Google reCAPTCHA
      responses:
        '200':
          description: Успешная регистрация, требуется подтверждение на сайте
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - action
                properties:
                  message:
                    type: string
                    example: 'Подтвердите действие на сайте'
                  action:
                    type: object
                    required:
                      - type
                      - label
                    properties:
                      type:
                        type: string
                        enum: [redirect, pressok]
                        example: 'pressok'
                      label:
                        type: string
                        example: 'OK'
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - details
                properties:
                  error:
                    type: string
                    example: 'Bad Request'
                  details:
                    type: string
                    example: 'Пароль не соответствует требованиям'
        '409':
          description: Пользователь уже существует
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - details
                properties:
                  error:
                    type: string
                    example: 'Conflict'
                  details:
                    type: string
                    example: 'Пользователь существует'
        '422':
          description: reCAPTCHA не подтверждена
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - details
                properties:
                  error:
                    type: string
                    example: 'Unprocessable Entity'
                  details:
                    type: string
                    example: 'Подтвердите reCAPTCHA'